alter table if exists to_do drop foreign key if exists FKhdf32h302ek7v92gs6h7hreil;
alter table if exists to_do drop foreign key if exists FK7em4k07c8u65es8eveh4bee4x;
drop table if exists category;
drop table if exists to_do;
drop table if exists users;
alter table if exists to_do drop foreign key if exists FKhdf32h302ek7v92gs6h7hreil;
alter table if exists to_do drop foreign key if exists FK7em4k07c8u65es8eveh4bee4x;
drop table if exists category;
drop table if exists to_do;
drop table if exists users;
